# Generated by Django 3.2.8 on 2021-10-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procesos',
            old_name='biblio',
            new_name='bibliotecario',
        ),
        migrations.RenameField(
            model_name='procesos',
            old_name='lect',
            new_name='lector',
        ),
    ]
