# Generated by Django 3.2.8 on 2021-10-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
        ('procesos', '0002_auto_20211029_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='proceso_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procesos.procesos'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='proceso_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procesos.procesos'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='bibliotecario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.bibliotecario'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='lector',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.lector'),
        ),
    ]
