# Generated by Django 3.2.8 on 2021-10-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_de_libro', models.CharField(help_text='introdusca titulo de Libro', max_length=77)),
                ('autor', models.CharField(help_text='Intrusca nombre de Autor', max_length=20)),
                ('editorial', models.CharField(blank=True, help_text='Intrusca editorial', max_length=20, null=True)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'ordering': ['-titulo_de_libro'],
            },
        ),
    ]
